### ISSUE TITLE
README installed apps

### ISSUE THREAD

**Issue by shakedown-street** [nanuxbe/django-classy-doc#2]
README is missing the step to add `"django_classy_doc"` to `INSTALLED_APPS`

Looks awesome btw!

**Comment by nanuxbe** [comment]
Hey, thank you for reporting the issue.

It has now been fixed by https://github.com/nanuxbe/django-classy-doc/commit/3ee3ee3f36519bc3bf0e462c1ed3a8dea1d35b9a
